apiVersion: v1
kind: ServiceAccount
metadata:
  name: plow-{{ .Values.deployment.nameSuffix }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: plow-{{ .Values.deployment.nameSuffix }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: plow-{{ .Values.deployment.nameSuffix }}
    service: plow-{{ .Values.deployment.nameSuffix }}
    expose: "{{ .Values.istio.exportService }}"
spec:
  ports:
  - port: {{ .Values.deployment.containerPort }}
    name: plow-http
  selector:
    app: plow-{{ .Values.deployment.nameSuffix }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plow-{{ .Values.deployment.nameSuffix }}
  name: plow-{{ .Values.deployment.nameSuffix }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: plow-{{ .Values.deployment.nameSuffix }}
  template:
    metadata:
      labels:
        app: plow-{{ .Values.deployment.nameSuffix }}
        istio.io/rev: {{ .Values.istio.revisionLabel }}
        sidecar.istio.io/inject: "{{ .Values.istio.inject }}"
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": {{ .Values.istio.holdProxy }} }'
    spec:
      serviceAccountName: plow-{{ .Values.deployment.nameSuffix }}
      containers:
      - name: plow-{{ .Values.deployment.nameSuffix }}
        image: ghcr.io/six-ddc/plow
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
          name: http-plow
        args:
        - {{ .Values.plow.url }}
        env:
        - name: PLOW_CONCURRENCY
          value: "{{ .Values.plow.concurrency }}"
        - name: PLOW_RATE
          value: "{{ .Values.plow.rate }}"
        - name: PLOW_REQUESTS
          value: "{{ .Values.plow.requests }}"
        - name: PLOW_DURATION
          value: "{{ .Values.plow.duration }}"
        - name: PLOW_INTERVAL
          value: "{{ .Values.plow.interval }}"
        - name: PLOW_METHOD
          value: "{{ .Values.plow.method }}"
        - name: PLOW_INSECURE
          value: "{{ .Values.plow.insecure }}"
        - name: PLOW_HEADER
          value: "{{ .Values.plow.additionalHeader }}"
        - name: PLOW_HOST
          value: "{{ .Values.plow.host }}"
