apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- base/rollouts-extension.yaml

components:
- github.com/argoproj-labs/argocd-extensions/manifests/?ref=main

namespace: argocd
  
images:
- name: quay.io/argoproj/argocd
  newTag: v2.4.17
  digest: sha256:24b95fcda18121c2e283054dcb84f16351a019d75d13447f3334f9fa233bebb3

patchesJson6902:
- path: overlays/application-controller-status-processors.yaml
  target:
    group: apps
    kind: StatefulSet
    name: argocd-application-controller
    version: v1

patchesStrategicMerge:
- overlays/argocd-cm.yaml
