plow:
  url: https://www.google.com
  concurrency: 1
  rate: 50 
  requests: -1
  duration: 0
  interval: 60
  method: GET
  insecure: true
  host: "google.com"
  additionalHeader: "user: solo"

deployment:
  nameSuffix: loadgenerator
  namespace: plow
  containerPort: 18888
  replicas: 1

istio:
  inject: true
  revisionLabel: 1-13
  holdProxy: true
  exportService: true

resources:
  requests: 
    cpu: 20m
    memory: 10Mi